server:
  port: 9000

spring:
  application:
     name: ribbon-cluster-controller

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/                #-- 去哪里注册